### ISSUE TITLE
Edhoc sample

### ISSUE THREAD

**Issue by eliot4321** [Fraunhofer-AISEC/uoscore-uedhoc#6]
Hi,

Is there a sample where OSCORE is using EDHOC as auth protocol?

**Comment by eliot4321** [comment]
@StefanHri  could you please assist with this?

**Comment by StefanHri** [comment]
Hi eliot4321,

Generally, OSCORE uses a symmetric key (the so called master secret) that needs to be established on both parties. The master secret can be established through edhoc, or some other method, e. g. during the production of the device. 

We don't have an example establishing the master secret through edhoc, however this can be easily constructed by combining the provided edhoc and oscore samples. Please check the dev branch and especially the Linux samples. 

I hope this helps. If you have more questions I will be happy to help. 

Stefan

**Comment by eliot4321** [comment]
Hi @StefanHri ,

Thanks for your reply!

I tried to combine the two samples but it seems there are some problems with declaration in edhoc.h and oscore.h, some variables are redeclared and the code fail to build.

**Comment by StefanHri** [comment]
Thanks for the feedback! Cann you be more concrete? What exactly is the problem?

**Comment by eliot4321** [comment]
When trying to include oscore.h and edhoc.h in the same file,  and trying to run the code.  I'm getting this error among other errors for other variables:
g++ -c -DEDHOC_WITH_TINYCRYPT_AND_C25519 -DEDHOC_DEBUG_PRINT -Isrc/ -I../../../externals/cantcoap/ -I../../../modules/edhoc/ -I../../../externals/tinycbor/src/ -I../../../externals/compact25519/src/c25519/ -I../../../externals/compact25519/src/ -I../../../externals/tinycrypt/lib/include -Og   -Wall -g -MMD -MP -MF"build/main.d"  src/main.cpp -o build/main.o
In file included from src/../../../../modules/oscore/oscore.h:20:0,
                 from src/main.cpp:29:
src/../../../../modules/oscore/inc/print_util.h:27:0: warning: "PRINT_ARRAY" redefined
 #define PRINT_ARRAY(msg, a, a_len) {};
 
In file included from src/../../../../modules/edhoc/edhoc.h:21:0,
                 from src/main.cpp:23:
src/../../../../modules/edhoc/inc/print_util.h:23:0: note: this is the location of the previous definition
 #define PRINT_ARRAY(msg, a, a_len)                                             \
 
In file included from src/../../../../modules/oscore/oscore.h:20:0,
                 from src/main.cpp:29:
src/../../../../modules/oscore/inc/print_util.h:28:0: warning: "PRINT_MSG" redefined
 #define PRINT_MSG(msg) {};
 
In file included from src/../../../../modules/edhoc/edhoc.h:21:0,
                 from src/main.cpp:23:
src/../../../../modules/edhoc/inc/print_util.h:26:0: note: this is the location of the previous definition
 #define PRINT_MSG(msg) printf(msg);
 
**In file included from src/../../../../modules/oscore/inc/security_context.h:17:0,
                 from src/../../../../modules/oscore/oscore.h:21,
                 from src/main.cpp:29:
src/../../../../modules/oscore/inc/supported_algorithm.h:17:2: error: redeclaration of ‘SHA_256’
  SHA_256,**

**Comment by StefanHri** [comment]
Are you using the dev branch?

**Comment by eliot4321** [comment]
no. for this one I used the main branch. But I assume redeclaration error will be the same if I'm trying to include edhoc.h and osocre.h in the same file.

**Comment by StefanHri** [comment]
Please use the dev branch.  In the dev branch I  fixed several errors which were occurring when building both oscore and edhoc . 

Moreover the dev branch contains an implementation of the current version of the edhoc standard. The main branch implements already a very old version.

**Comment by eliot4321** [comment]
Thanks, I will try the dev branch and get back to you. Thanks again for your support!

**Comment by StefanHri** [comment]
Thanks as well from my side for providing feedback!

I am interested to understand what is the project where you use OSCORE and EDHOC. We are discussing future improvements and directions of developing this project. Therefore, I will be happy to get in touch with you and understand your use case. Do you have ca. 30 min after 25.01 for a talk? 

Thanks
Stefan

**Comment by eliot4321** [comment]
Thanks, we want to run some measurements to evaluate oscore and edhoc.

**Comment by StefanHri** [comment]
Did you check already our paper https://arxiv.org/abs/2103.13832? Here we have evaluation results regarding execution speed, flash, ram and power consumption.

**Comment by eliot4321** [comment]
Yes I have checked the publication and it's a very interesting one. For our work, we are focusing on the network side.

**Comment by eliot4321** [comment]
Hi @StefanHri ,

It seems I cannot clone the jsmn.git repository, as I don't have access, I cannot clone all the submodules for the dev branch.

**Comment by StefanHri** [comment]
You may need to upload your public ssh key to github

**Comment by eliot4321** [comment]
Hi @StefanHri ,

I have tried to run the oscore_linux /client but I'm getting too many errors, please see below. Have you tried to compile from your side?

src/main.cpp: In function ‘int main()’:
src/main.cpp:75:49: error: ‘AES_CCM_16_64_128’ was not declared in this scope

**Comment by StefanHri** [comment]
I fix it. Pull the dev branch and all should work

**Comment by eliot4321** [comment]
Thanks, I'm sorry I have noticed your invitation for a call but I missed it, of course,
 we can have a call it will be very nice to share our thoughts.

**Comment by eliot4321** [comment]
It's working thanks, just one issue that I fixed the path to "test_vectors/edhoc-vectors-json_v11.txt" in responser/src/main.cpp and initiator/src/main.cpp is incorrect.  
I will try now to integrate the oscore with edhoc and let you know.

**Comment by eliot4321** [comment]
Hi @StefanHri ,

I have played around with the samples code but still I  got too many errors when I'm trying to merge the edhoc and the oscore code.  If you have an already example of oscore using edhoc,  could you please point to it directly?

Thanks in advance.

**Comment by StefanHri** [comment]
I am from 10 to 25 of January on vacation. After that I can set up a sample showing the combination of both. Will this fit to your schedule? After 25.01 we can also arrange a call. You can already send me your preferred dates per email at stefan.hristozov@aisec.fraunhofer.de.

Br,
Stefan

**Comment by eliot4321** [comment]
Hi @StefanHri ,

I hope you enjoyed your vacation,
I was trying to solve the issues I had while trying to run Edhoc with Oscore but I didn't succeed,  could you please provide me with the right script for it? Thanks in advance.

**Comment by StefanHri** [comment]
Hi @eliot4321,

I will prepare an example and let you know.

**Comment by StefanHri** [comment]
hi @eliot4321 

see https://github.com/Fraunhofer-AISEC/uoscore-uedhoc/tree/combo_sample/samples/linux_edhoc_oscore

This is a sample showing:

* deriving a master secret and master salt with EDHOC
* using those to protect CoAP with OSCORE

Is this what you are looking for?

**Comment by eliot4321** [comment]
Hi @StefanHri ,

Thanks a lot for the effort, much appreciated! I will check the code, try it and get back to you soon.

**Comment by eliot4321** [comment]
Hi @StefanHri ,

I have tried the scripts it's working, thanks! 
I have a question regarding the response coming from the server, is it an unprotected response? at least that's what the logs are showing.
I understand from the logs that the client is sending a protected CoAP request with OSCORE, but it's not the same for the response coming from the server.

**Comment by StefanHri** [comment]
It should be alternating. The  client sends one CoAp packet - - the server responds with CoAp. Than the client sends OSCORE - - the server responds with OSCORE. It is like that as well in the oscore sample. I copied it from there. You can check if this is truly the case with Wireshark or tcpdump. I did not check that. If this is not the case let me know.

**Comment by StefanHri** [comment]
Hi @eliot4321, 
I merged the sample in the dev branch and will close this issue. If you have other problems please open a new issue. If you like the project we will be happy if you can give it a star.
