### ISSUE TITLE
Tests and Zephyr CI

### ISSUE THREAD

**Issue by StefanHri** [Fraunhofer-AISEC/uoscore-uedhoc#9]
Feedback form Zephyr:

"I’ve also moved the unit test into the Zephyr tree, to verify the results. The whole project is now built entirely by Zephyr build system, it can be build for `native_posix` for example. I believe we should have some minimal set of tests in Zephyr tree, to ensure that the libraries can build and run correctly in the Zephyr CI, the current solution seems to be a bit complex to be honest to be integrated as a Zephyr test suite – I could build it for other plaforms for example due to lack of `fopen` etc. functionalities it makes use of. I think this is a topic for discussion how to verify the lib functionality in the CI."

**Comment by StefanHri** [comment]
File system functions are used as well by mbedtls. Disabling them causes PSA_ERROR_INSUFFICIENT_ENTROPY. Any ideas how to deal with that @rlubos?

**Comment by rlubos** [comment]
It seems that mbedTLS comes with some default file-system-based entropy implementation that gets enabled with the default config.

We should likely register an entropy source with `mbedtls_entropy_add_source()` - Zephyr has it's own entorpy driver, so it could likely be a thin wrapper (https://github.com/zephyrproject-rtos/zephyr/blob/main/include/drivers/entropy.h). Ideally, Zepyr could take care of this at system boot, but it's no implemented - we can add this to the mbedTLS requirements list.

I found an example entropy function based on Zephyr entoropy subsys that could be used as a reference in our old NCS code (https://github.com/nrfconnect/sdk-nrfxlib/blob/main/nrf_security/src/legacy/entropy_poll.c#L13).

**Comment by StefanHri** [comment]
I got the example `(https://github.com/nrfconnect/sdk-nrfxlib/blob/main/nrf_security/src/legacy/entropy_poll.c#L13)` to compile for nrf52840_mdk. However, I don't have such a board here. For nrf9160dk_nrf9160 (that I have here) I am getting  `error: 'DT_CHOSEN_ZEPHYR_ENTROPY_LABEL' undeclared (first use in this function)`. 

Is it possible to set the body of the function so that it runs on different platforms only for the sake of testing (of course not providing real entropy)?

**Comment by rlubos** [comment]
This is happening because nRF91 makes use of CryptoCell entropy, which is not available in the vanilla Zephyr (closed source libraries), only in nRF Connect SDK context. One possible option for testing could be to use RNG instead of the entropy subsys - just enable `CONFIG_TEST_RANDOM_GENERATOR=y` and use Zephyr [random API](https://github.com/zephyrproject-rtos/zephyr/blob/main/include/random/rand32.h#L60) to fill the requested buffer.

**Comment by StefanHri** [comment]
I am trying to get the tests running with mbedtls coming from Zephyr (not as git submodule as for now) what do I need to put in my prj.conf file? For now, I have:
```
CONFIG_ZTEST=y
CONFIG_ZTEST_STACKSIZE=10240
CONFIG_TEST_RANDOM_GENERATOR=y
CONFIG_MBEDTLS=y
```

However, it looks like the PSA functions are not available and I cannot find a config to turn them on [here](https://docs.zephyrproject.org/latest/reference/kconfig/index-all.html?highlight=config_mbedtls_cfg_file#all-configuration-options).

**Comment by rlubos** [comment]
We don't have an option to enable PSA with Kconfig yet - you need to use a custom mbed TLS config file with PSA enabled:
https://github.com/rlubos/zephyr/blob/oscore-test/tests/lib/uoscore_uedhoc/prj.conf#L8
https://github.com/rlubos/zephyr/blob/oscore-test/modules/mbedtls/configs/config-oscore-edhoc.h
The config file posted above is just the default config file shipped with mbed TLS with PSA enabled.

**Comment by StefanHri** [comment]
OK, understand. In that case, it will be best to provide an option for enabling the required mbedtls functions together with uoscore-uedhoc. The [readme](https://github.com/Fraunhofer-AISEC/uoscore-uedhoc/tree/dev#supported-cipher-suites) documents which crypto algorithms we need.

In the meantime, in order to test on different architectures before we have uoscore-uedhoc integrated, we will proceed to use mbedtls as a submodule. For that, I need some simple configuration for the random number generator which works on different platforms, native_posix, nrfxx, and so on. We don't need real random numbers we need something just to make mbedtls work.

Do you know how to achieve such a configuration by modifying only the mbedtls_config.h?

**Comment by rlubos** [comment]
I think that the solution we use in TLS sockets could be used as a reference here:
https://github.com/zephyrproject-rtos/zephyr/blob/main/subsys/net/lib/sockets/sockets_tls.c#L225
This approach works with any platforms - if the platform provides an entropy driver, a cryptographically secure RNG is used, otherwise we fallback to a non-secure RNG.

**Comment by StefanHri** [comment]
solved
